### ISSUE TITLE
automatic merge script can't handle again

### ISSUE THREAD

**Issue by y6x2digc** [mikroskeemsrealm/Firefly#16]
It can't handle https://github.com/PaperMC/Waterfall/commit/7b4d6e99a98216175470bdb3c0f8c4cc3563a78b

**Comment by mikroskeem** [comment]
As I'm not near my computer for next few days then quick PR by someone would help.

**Comment by mikroskeem** [comment]
8a0beb23481562792fce0f89afb27db8cdccdb22
